//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WJP_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WJP_Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email succesfull!.
        /// </summary>
        public static string ChangeEmailSuc {
            get {
                return ResourceManager.GetString("ChangeEmailSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ChangePassCompFail {
            get {
                return ResourceManager.GetString("ChangePassCompFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ChangePassConf {
            get {
                return ResourceManager.GetString("ChangePassConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePassCurr {
            get {
                return ResourceManager.GetString("ChangePassCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password must be at least 7 characters long.
        /// </summary>
        public static string ChangePassLength {
            get {
                return ResourceManager.GetString("ChangePassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePassNewPass {
            get {
                return ResourceManager.GetString("ChangePassNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length of new password: .
        /// </summary>
        public static string ChangePassReq {
            get {
                return ResourceManager.GetString("ChangePassReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string ChangePassSuc {
            get {
                return ResourceManager.GetString("ChangePassSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string ChangePassUnsuc {
            get {
                return ResourceManager.GetString("ChangePassUnsuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string ChangePasswordFail {
            get {
                return ResourceManager.GetString("ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show deprecation.
        /// </summary>
        public static string CompileDeprecation {
            get {
                return ResourceManager.GetString("CompileDeprecation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Result.
        /// </summary>
        public static string CompileDownload {
            get {
                return ResourceManager.GetString("CompileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to email.
        /// </summary>
        public static string CompileEmail {
            get {
                return ResourceManager.GetString("CompileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some errors during compilation, please check log..
        /// </summary>
        public static string CompileErrors {
            get {
                return ResourceManager.GetString("CompileErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string CompileResult {
            get {
                return ResourceManager.GetString("CompileResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Compiler version.
        /// </summary>
        public static string CompileVersion {
            get {
                return ResourceManager.GetString("CompileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warnings.
        /// </summary>
        public static string CompileWarnings {
            get {
                return ResourceManager.GetString("CompileWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that email address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was sent. 
        ///
        ///If you haven&apos;t got it, wait a few minutes, or your email adress was incorrect, or our site is wrong ((.
        /// </summary>
        public static string EmailMessage {
            get {
                return ResourceManager.GetString("EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Java online project system. You can create compile your Java projects here. Also you can do bla-bla-bla....
        /// </summary>
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect, or your account is blocked by administrator..
        /// </summary>
        public static string IncorrectLoginOrPass {
            get {
                return ResourceManager.GetString("IncorrectLoginOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as.
        /// </summary>
        public static string LogInMess {
            get {
                return ResourceManager.GetString("LogInMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to log on into system!.
        /// </summary>
        public static string LogOnError {
            get {
                return ResourceManager.GetString("LogOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string LogOnName {
            get {
                return ResourceManager.GetString("LogOnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogOnPass {
            get {
                return ResourceManager.GetString("LogOnPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LogOnRemember {
            get {
                return ResourceManager.GetString("LogOnRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and password..
        /// </summary>
        public static string PleaseLogOn {
            get {
                return ResourceManager.GetString("PleaseLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string ProfileProjects {
            get {
                return ResourceManager.GetString("ProfileProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        public static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string ProfileStats {
            get {
                return ResourceManager.GetString("ProfileStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string ProjectAddUser1 {
            get {
                return ResourceManager.GetString("ProjectAddUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to my project..
        /// </summary>
        public static string ProjectAddUser2 {
            get {
                return ResourceManager.GetString("ProjectAddUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this user to my project.
        /// </summary>
        public static string ProjectAddUserToProject {
            get {
                return ResourceManager.GetString("ProjectAddUserToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My related projects.
        /// </summary>
        public static string ProjectAllowed {
            get {
                return ResourceManager.GetString("ProjectAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block user.
        /// </summary>
        public static string ProjectBlockUser {
            get {
                return ResourceManager.GetString("ProjectBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your project.
        /// </summary>
        public static string ProjectChooseYourProject {
            get {
                return ResourceManager.GetString("ProjectChooseYourProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ProjectClosed {
            get {
                return ResourceManager.GetString("ProjectClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile.
        /// </summary>
        public static string ProjectCompile {
            get {
                return ResourceManager.GetString("ProjectCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of created projects.
        /// </summary>
        public static string ProjectCreatedNumber {
            get {
                return ResourceManager.GetString("ProjectCreatedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string ProjectCreateProject {
            get {
                return ResourceManager.GetString("ProjectCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data files.
        /// </summary>
        public static string ProjectData {
            get {
                return ResourceManager.GetString("ProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ProjectExit {
            get {
                return ResourceManager.GetString("ProjectExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string ProjectFileCreatedBy {
            get {
                return ResourceManager.GetString("ProjectFileCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string ProjectFileCreatedDate {
            get {
                return ResourceManager.GetString("ProjectFileCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ProjectFileDelete {
            get {
                return ResourceManager.GetString("ProjectFileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ProjectFileDownload {
            get {
                return ResourceManager.GetString("ProjectFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ProjectFileEdit {
            get {
                return ResourceManager.GetString("ProjectFileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string ProjectFileModifiedBy {
            get {
                return ResourceManager.GetString("ProjectFileModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified date.
        /// </summary>
        public static string ProjectFileModifiedDate {
            get {
                return ResourceManager.GetString("ProjectFileModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string ProjectFileName {
            get {
                return ResourceManager.GetString("ProjectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files added.
        /// </summary>
        public static string ProjectFilesAdded {
            get {
                return ResourceManager.GetString("ProjectFilesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new.
        /// </summary>
        public static string ProjectFileUpload {
            get {
                return ResourceManager.GetString("ProjectFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find projects.
        /// </summary>
        public static string ProjectFindProjects {
            get {
                return ResourceManager.GetString("ProjectFindProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find users.
        /// </summary>
        public static string ProjectFindUsers {
            get {
                return ResourceManager.GetString("ProjectFindUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string ProjectGeneral {
            get {
                return ResourceManager.GetString("ProjectGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project logo image.
        /// </summary>
        public static string ProjectImage {
            get {
                return ResourceManager.GetString("ProjectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of joined projects.
        /// </summary>
        public static string ProjectJoinedNumber {
            get {
                return ResourceManager.GetString("ProjectJoinedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changes.
        /// </summary>
        public static string ProjectLastChanges {
            get {
                return ResourceManager.GetString("ProjectLastChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last project.
        /// </summary>
        public static string ProjectLastProject {
            get {
                return ResourceManager.GetString("ProjectLastProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library files.
        /// </summary>
        public static string ProjectLibrary {
            get {
                return ResourceManager.GetString("ProjectLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name must be at least 5 characters long.
        /// </summary>
        public static string ProjectNameLength {
            get {
                return ResourceManager.GetString("ProjectNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My own projects.
        /// </summary>
        public static string ProjectOwn {
            get {
                return ResourceManager.GetString("ProjectOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectProject {
            get {
                return ResourceManager.GetString("ProjectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source files.
        /// </summary>
        public static string ProjectSource {
            get {
                return ResourceManager.GetString("ProjectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock user.
        /// </summary>
        public static string ProjectUnblockUser {
            get {
                return ResourceManager.GetString("ProjectUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegEmail {
            get {
                return ResourceManager.GetString("RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string RegUnsuc {
            get {
                return ResourceManager.GetString("RegUnsuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name must be at least 3 characters long.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
    }
}
